# Generated by Django 3.1.7 on 2021-03-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('catcode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catcode', models.CharField(max_length=5)),
                ('task', models.CharField(default='Enter A Task Definition', max_length=60)),
                ('taskcode', models.CharField(default=100, max_length=30)),
            ],
        ),
    ]
