# Generated by Django 3.1.7 on 2021-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdcode', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[("('NS', 'Not-Started')", 'Notstarted'), ("('OG', 'Ongoing')", 'Ongoing'), ('CP', 'Completed')], max_length=30)),
                ('start', models.DateField()),
                ('end', models.DateField(null=True)),
                ('duration', models.DurationField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[("('UI', 'Urgent-Important')", 'Urgimp'), ("('UU', 'Urgent-Unimportant')", 'Urgunimp'), ("('NI', 'NotUrgent-Important')", 'Noturgimp'), ('NU', 'NotUrgent-Unimportant')], default="('UU', 'Urgent-Unimportant')", max_length=40)),
                ('taskcode', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[("('NS', 'Not-Started')", 'Notstarted'), ("('OG', 'Ongoing')", 'Ongoing'), ('CP', 'Completed')], default="('NS', 'Not-Started')", max_length=30)),
                ('activity', models.CharField(max_length=300)),
                ('tdcode', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='taskcode',
            field=models.CharField(max_length=30),
        ),
    ]
