# Generated by Django 3.1.7 on 2021-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmgr', '0002_auto_20210321_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetasks',
            name='status',
            field=models.CharField(choices=[("('NS', 'Not_Started')", 'Notstarted'), ("('OG', 'Ongoing')", 'Ongoing'), ('CP', 'Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[("('NS', 'Not_Started')", 'Notstarted'), ("('OG', 'Ongoing')", 'Ongoing'), ('CP', 'Completed')], default="('NS', 'Not_Started')", max_length=30),
        ),
    ]
