# Generated by Django 3.1.7 on 2021-03-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Enter Category Name', max_length=40)),
                ('description', models.CharField(default='Enter Category Description', max_length=300)),
                ('catcode', models.CharField(default=100, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Enter A Task Definition', max_length=60)),
                ('taskcode', models.CharField(default=100, max_length=30)),
                ('catcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskcategory', to='tasks.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[("('UI', 'Urgent-Important')", 'Urgimp'), ("('UU', 'Urgent-Unimportant')", 'Urgunimp'), ("('NI', 'NotUrgent-Important')", 'Noturgimp'), ('NU', 'NotUrgent-Unimportant')], default="('UU', 'Urgent-Unimportant')", max_length=40)),
                ('status', models.CharField(choices=[("('NS', 'Not-Started')", 'Notstarted'), ("('OG', 'Ongoing')", 'Ongoing'), ('CP', 'Completed')], default="('NS', 'Not-Started')", max_length=30)),
                ('activity', models.CharField(default='Enter Specific Activity related to the task', max_length=300)),
                ('todocode', models.CharField(default=100, max_length=30)),
                ('taskcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='tasks.tasklist')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[("('NS', 'Not-Started')", 'Notstarted'), ("('OG', 'Ongoing')", 'Ongoing'), ('CP', 'Completed')], max_length=30)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('duration', models.DurationField()),
                ('todocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activetasks', to='tasks.todo')),
            ],
        ),
    ]
